# Generated by Django 4.2.13 on 2024-09-14 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_alter_student_roll_number_alter_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
