# Generated by Django 5.2 on 2025-07-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myclass',
        ),
    ]
