# Generated by Django 4.2.13 on 2024-09-15 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_student_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registered_by',
        ),
        migrations.AddField(
            model_name='student',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
